### ISSUE TITLE
difficulty sending data to elm from rust

### ISSUE THREAD

**Issue by bburdette** [whodidthis/testing-elm-websockets#1]
I gather from the mailing list that you are using Elm with rust?  I am trying to do the same.  I have a little test prog that successfully receives messages from the elm-sockets example program.  But replies are not shown.  According to the chromium debugger, the reply messages arrive in the browser, but their contents are not printed in the status string in elm.  I've looked at the code a bit but nothing really stands out as an obvious problem to me.  

I made a little test program if you'd like to take a look.  Its here:

https://github.com/bburdette/socktest

It receives and prints the char messages from Main.Elm, and sends back reply strings.  

To use, just build it with cargo build, then run ./target/debug/socktest, then do elm-reactor in the elm-sockets dir and run the elm-sockets test.  

Thanks!

**Comment by whodidthis** [comment]
I gave up on this already T_T

https://github.com/whodidthis/elm-sockets/commit/3200a8d9c355ad5b41da12392560693a61824ea4 I wrote this commit message so as long as you comment out `port connection` sending and receiving messages should probably work.

**Comment by bburdette** [comment]
yay that works!  I guess I can do without the 'connected' thing for now, receiving msgs more important.

**Comment by whodidthis** [comment]
As a side node i found this rust lib has a pretty sweet api for websockets https://github.com/housleyjk/ws-rs.

**Comment by bburdette** [comment]
Hey!  I think I solved it.  My solution:
```
port listening : Task x (List ())
port listening = socket `Task.andThen`
  (\s ->
    Task.sequence [WebSocket.listen listen.address s,
                   WebSocket.connected connected.address s])
```

And then comment/get rid of the 'connection' port:

```
-- port connection : Task x ()
-- port connection = socket `Task.andThen` WebSocket.connected connected.address
```

My theory here is that there is another socket being created, so that the connected uses one and the listening uses another.  By chance, messages get sent to the 'connected' one and listening receives nothing.  Or something like that.  Anyway passing the same socket to both works for me.

**Comment by bburdette** [comment]
what I don't understand is what about the 'send' socket?  is that created each time?  It seems like not.  but anyway it works now.
